name: Test2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      BIN_PATH: /home/runner/work/my-openwrt/my-openwrt

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Build Environment Initialization
        run: |
          sudo apt-get -qq remove --purge mysql* php* google* firefox ghc azure-cli \
          dotnet* powershell ruby-full zulu* hhvm llvm*

          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /var/lib/docker
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/hostedtoolcache/go /opt/hostedtoolcache/Ruby /opt/hostedtoolcache/node

          sudo apt-get install -qq -y squashfs-tools

          sudo apt-get -qq autoremove --purge
          sudo apt-get -qq clean
          df -h

      - name: Cache immortalwrt.img
        uses: actions/cache@v2
        with:
          path: |
            immortalwrt.img
          key: ${{ runner.os }}-${{ hashFiles('immortalwrt.img') }}

      - name: Test Cache
        run: |
          ls -l --block-size=M
          df -h
          sudo mount -t immortalwrt.img /home/runner/work/my-openwrt/my-openwrt/immortalwrt -o loop
          ls
          ls -l --block-size=M