name: Test2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      BIN_PATH: /home/runner/work/my-openwrt/my-openwrt

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Cache immortalwrt.img
        uses: actions/cache@v2
        with:
          path: |
            immortalwrt.img
          key: ${{ runner.os }}-${{ hashFiles('immortalwrt.img') }}

      - name: Test Cache
        run: |
          ls -l --block-size=M
          df -h
          sudo mount -t immortalwrt.img /home/runner/work/my-openwrt/my-openwrt/immortalwrt -o loop
          ls
          ls -l --block-size=M