name: Build-OpenWrt-ImmortalWrt

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 15 * * 1,2,4,5,6'
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CI_TOKEN: ${{ secrets.GHCI_TOKEN }}

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: cli
        run: |
          gh auth login --with-token ${CI_TOKEN}