name: Build-Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 15 * * 1,2,4,5,6'
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: wget
        run: |
          wget https://github.com/ibook86/my-openwrt/releases/download/kernel-5.4.150/immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin